Actualización en la documentación de la página web
grupoioa/gis_agm_series pull request #84
Opened 2022-03-01 19:02 UTC by MaCuur

Añadí título a la página web también

2022-03-01 20:50 UTC, ma-robles requested changes
ya salen los cambios en docs, pero sigue apareciendo la carpeta Doc y una modificacion en el .html. Debes borrar la carpeta Doc antes de hacer el commit (si puedes también eliminar el cambio en el html pero ese no es tan importante). También te faltó el PDF, si es que ya lo tuvieras :)

2022-03-02 05:33 UTC, ma-robles approved these changes

2022-03-02 20:12 UTC, ma-robles requested changes
Te faltó agregar las imagenes en la carpeta img/

2022-03-02 20:20 UTC, MaCuur commented
> 

listo 👀

2022-03-02 20:25 UTC, merged